### ISSUE TITLE
Add Dependabot configuration for automated dependency updates

### ISSUE THREAD

**Issue by rgf2004** [rgf2004/whatsapp-marketing-tool#6]
## Description
Configure Dependabot to automatically monitor and update project dependencies across both frontend and backend packages. This will help maintain security and keep dependencies current.

## Current State
- Dependencies are manually updated
- No automated security vulnerability monitoring
- Risk of outdated packages with security issues
- Manual effort required to track dependency updates

## Proposed Solution
Add Dependabot configuration to automatically:
- Monitor package.json files in both frontend and backend
- Check for updates daily
- Create pull requests for dependency updates
- Group related updates when possible
- Handle both regular and security updates

### Dependabot Configuration File
Create `.github/dependabot.yml` with:
- **Package Ecosystems**: npm for both frontend and backend
- **Update Schedule**: Daily checks
- **Directory Monitoring**: Root, frontend/, and backend/ directories
- **Grouping Strategy**: Group patch updates, separate major updates
- **Security Updates**: Prioritize security patches

### Configuration Details
- **Update Frequency**: Daily at a convenient time
- **PR Limits**: Reasonable limit to avoid spam
- **Auto-merge**: Consider auto-merge for patch updates
- **Reviewers**: Assign appropriate reviewers if needed
- **Labels**: Add appropriate labels for easy identification

## Acceptance Criteria
- [ ] `.github/dependabot.yml` configuration file created
- [ ] Monitors package.json in root directory
- [ ] Monitors frontend/package.json
- [ ] Monitors backend/package.json  
- [ ] Daily update schedule configured
- [ ] Security updates prioritized
- [ ] Reasonable PR limits set
- [ ] Appropriate grouping of related updates
- [ ] Labels configured for easy identification
- [ ] Documentation updated with Dependabot information

## Benefits
- **Security**: Automatic security vulnerability patches
- **Maintenance**: Reduced manual effort for dependency updates
- **Stability**: Regular updates prevent large breaking changes
- **Monitoring**: Clear visibility of dependency status via PRs

## Example Configuration Structure
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" 
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
```

## Priority
Medium - Important for security and maintenance but not blocking core features

## Files to Create
- `.github/dependabot.yml`
- Update documentation mentioning automated dependency management

---
*This issue was created by Claude AI based on user input*
